# This rule is not used by the project nebularr itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the arr.rinzler.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nebularr
    app.kubernetes.io/managed-by: kustomize
  name: lidarrconfig-editor-role
rules:
- apiGroups:
  - arr.rinzler.cloud
  resources:
  - lidarrconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arr.rinzler.cloud
  resources:
  - lidarrconfigs/status
  verbs:
  - get
