---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arr.rinzler.cloud
  resources:
  - bazarrconfigs
  - downloadstackconfigs
  - lidarrconfigs
  - prowlarrconfigs
  - radarrconfigs
  - readarrconfigs
  - sonarrconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arr.rinzler.cloud
  resources:
  - bazarrconfigs/finalizers
  - downloadstackconfigs/finalizers
  - lidarrconfigs/finalizers
  - prowlarrconfigs/finalizers
  - radarrconfigs/finalizers
  - readarrconfigs/finalizers
  - sonarrconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - arr.rinzler.cloud
  resources:
  - bazarrconfigs/status
  - downloadstackconfigs/status
  - lidarrconfigs/status
  - prowlarrconfigs/status
  - radarrconfigs/status
  - readarrconfigs/status
  - sonarrconfigs/status
  verbs:
  - get
  - patch
  - update
